project:
  type: website

execute:
  freeze: auto
  echo: true

# format:
#   html:
#     theme: 
#       - default
#       - custom.scss
#     toc-depth: 2
#     notebook-links: global
#     number-sections: false

  # repo-url: "https://github.com/munch-group/libraryname"
  # repo-actions: [edit, issue, source]  
  # title: "Docs for libraryname"
  # author: "Kasper Munch"  

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

# # tell quarto to read the generated styles
# format:
#   css: _styles-quartodoc.css

quartodoc:
  package: libraryname

  # write sidebar and style data
  sidebar: _sidebar.yml
  css: _styles-quartodoc.css

  sections:
    - title: Some section
      desc: ""
      contents:
        - foo        # function: quartodoc.get_object
        - bar.baz       # submodule func: quartodoc.ast.preview
