project:
  type: book

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

book:
  repo-url: "https://github.com/munch-group/libraryname"
  repo-actions: [edit, issue, source]  
  title: "Docs for libraryname"
  author: "Kasper Munch"  
  chapters:
    - index.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/example.ipynb
